# Generated by Django 5.2.5 on 2025-08-22 16:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Rede')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Rede',
                'verbose_name_plural': 'Redes',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Projeto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('tecnologia', models.CharField(choices=[('Vue', 'Vue.js'), ('Django', 'Django REST Framework')], max_length=100, verbose_name='Tecnologia Principal')),
                ('source_type', models.CharField(choices=[('git', 'Repositório Git'), ('docker_image', 'Imagem Docker')], max_length=20, verbose_name='Tipo de Fonte')),
                ('source_url', models.URLField(verbose_name='URL da Fonte')),
                ('porta', models.IntegerField(verbose_name='Porta')),
                ('variaveis_ambiente', models.JSONField(blank=True, null=True, verbose_name='Variáveis de Ambiente')),
                ('dominio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Domínio do site')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_andamento', 'Em Andamento'), ('pronto', 'Pronto'), ('abortado', 'Abortado'), ('erro', 'Erro')], default='rascunho', max_length=20, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('url_deploy', models.URLField(blank=True, null=True, verbose_name='URL do Deploy')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='project_django_app.network', verbose_name='Rede')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-data_ultima_atualizacao'],
            },
        ),
    ]
