# Generated by Django 5.2.5 on 2025-08-07 18:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Projeto')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('tecnologia', models.CharField(choices=[('Vue', 'Vue.js'), ('Django', 'Django REST Framework')], max_length=100, verbose_name='Tecnologia Principal')),
                ('tipo_fonte', models.CharField(choices=[('Docker', 'Imagem docker '), ('Github', 'Repositório GitHub')], default='Github', max_length=20, verbose_name='Tipo de Fonte')),
                ('github_repo', models.URLField(verbose_name='URL do Repositório GitHub')),
                ('github_branch', models.CharField(default='main', max_length=100, verbose_name='Branch do GitHub')),
                ('github_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token do GitHub (caso o repostório seja privado)')),
                ('image_repo', models.CharField(max_length=100, verbose_name='Repositorio da imagem(Dockerbub)')),
                ('image_tag', models.CharField(max_length=50, verbose_name='Tag da imagem')),
                ('porta_personalizada', models.IntegerField(blank=True, null=True, verbose_name='Porta Personalizada')),
                ('variaveis_ambiente', models.JSONField(blank=True, null=True, verbose_name='Variáveis de Ambiente')),
                ('status', models.CharField(choices=[('Pendente', 'pendente'), ('Concluido', 'enviado'), ('Em andamento', 'em andamento')], default='rascunho', max_length=20)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('url_deploy', models.URLField(blank=True, null=True, verbose_name='URL do Deploy')),
                ('dominio', models.CharField(editable=False, max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-data_ultima_atualizacao'],
            },
        ),
    ]
