# Generated by Django 5.2.5 on 2025-08-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='dominio',
            field=models.CharField(max_length=100),
        ),
    ]
