# Generated by Django 5.2.5 on 2025-08-31 06:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_django_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nome do Projeto')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('technology', models.CharField(choices=[('Vue', 'Vue.js'), ('Django', 'Django REST Framework')], max_length=100, verbose_name='Tecnologia')),
                ('source_type', models.CharField(choices=[('git', 'Github'), ('docker', 'Dockerhub')], max_length=20, verbose_name='Fonte do código')),
                ('source_git', models.URLField(verbose_name='Repositório do Github')),
                ('source_docker', models.CharField(blank=True, null=True, verbose_name='Imagem do Dockerhub')),
                ('port', models.IntegerField(verbose_name='Porta')),
                ('variables', models.JSONField(blank=True, null=True, verbose_name='Variáveis de Ambiente')),
                ('domain', models.CharField(blank=True, max_length=100, null=True, verbose_name='Domínio do site')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('last_update_date', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='project_django_app.network', verbose_name='Rede')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-last_update_date'],
            },
        ),
        migrations.DeleteModel(
            name='Projeto',
        ),
    ]
