# Generated by Django 5.2.5 on 2025-08-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_django_app', '0002_alter_projeto_dominio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='dominio',
            field=models.CharField(max_length=100, verbose_name='Domínio do site'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='github_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token do GitHub (caso o repositório seja privado)'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='image_repo',
            field=models.CharField(max_length=100, verbose_name='Repositório da imagem (DockerHub)'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('concluido', 'Concluído'), ('em_andamento', 'Em andamento')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tipo_fonte',
            field=models.CharField(choices=[('Docker', 'Imagem Docker'), ('Github', 'Repositório GitHub')], default='Github', max_length=20, verbose_name='Tipo de Fonte'),
        ),
    ]
