# Generated by Django 5.2.5 on 2025-08-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_django_app', '0003_alter_projeto_dominio_alter_projeto_github_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='github_token',
        ),
        migrations.AlterField(
            model_name='projeto',
            name='image_repo',
            field=models.CharField(max_length=200, verbose_name='Repositório da imagem (ex: usuario/repo ou registry/repo)'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='image_tag',
            field=models.CharField(default='latest', max_length=50, verbose_name='Tag da imagem'),
        ),
    ]
