# Generated by Django 5.2.5 on 2025-08-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_django_app', '0004_remove_projeto_github_token_alter_projeto_image_repo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='dominio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Domínio do site'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='github_branch',
            field=models.CharField(blank=True, default='main', max_length=100, null=True, verbose_name='Branch do GitHub'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='github_repo',
            field=models.URLField(blank=True, null=True, verbose_name='URL do Repositório GitHub'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='image_repo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Repositório da imagem (ex: usuario/repo ou registry/repo)'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='image_tag',
            field=models.CharField(blank=True, default='latest', max_length=50, null=True, verbose_name='Tag da imagem'),
        ),
    ]
