# Generated by Django 5.2.8 on 2025-11-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_app_options_alter_app_table_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
