# Generated by Django 5.2.8 on 2025-11-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_service_delete_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('postgres', 'Postgres'), ('rabbitmq', 'RabbitMQ'), ('redis', 'Redis')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
