# Generated by Django 5.2.1 on 2025-11-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_service_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='name_dokku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
