# Generated by Django 5.2.8 on 2025-11-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_app_name_dokku'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='branch',
            field=models.CharField(default='main', max_length=255),
        ),
    ]
