# Generated by Django 5.2.8 on 2025-11-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_add_branch_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='status',
            field=models.CharField(choices=[('starting', 'Starting'), ('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error')], default='stopped', max_length=50),
        ),
    ]
