# Generated by Django 5.2.8 on 2025-12-01 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_alter_app_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='status',
            field=models.CharField(choices=[('starting', 'Starting'), ('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error'), ('deleting', 'Deleting')], default='stopped', max_length=50),
        ),
    ]
