# Generated by Django 5.2.8 on 2025-12-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_alter_app_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='container_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='status',
            field=models.CharField(choices=[('starting', 'Starting'), ('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error'), ('deleting', 'Deleting'), ('deploying', 'Deploying')], default='stopped', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='user',
            field=models.CharField(default='postgres', max_length=255),
        ),
    ]
