# Generated by Django 5.2.8 on 2025-12-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_service_container_name_alter_app_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='status',
            field=models.CharField(choices=[('STARTING', 'Starting'), ('RUNNING', 'Running'), ('STOPPED', 'Stopped'), ('STOPPING', 'Stopping'), ('RESTARTING', 'Restarting'), ('ERROR', 'Error'), ('DELETING', 'Deleting'), ('DEPLOYING', 'Deploying')], default='STOPPED', max_length=50),
        ),
    ]
