# Generated by Django 5.2.8 on 2026-02-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_alter_app_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='error_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='error_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='help_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
