# Generated by Django 5.2.1 on 2026-02-26 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_app_error_details_app_error_type_app_help_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='apps.app'),
        ),
    ]
