# Generated by Django 5.2.8 on 2026-03-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_service_task_id_alter_service_app'),
        ('project', '0002_alter_project_options_remove_project_user_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['name'], name='idx_app_name'),
        ),
        migrations.AddConstraint(
            model_name='app',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_app_name'),
        ),
    ]
