# Generated by Django 5.2.1 on 2026-04-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_app_idx_app_name_app_unique_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='last_commit_sha',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
