# Generated by Django 5.2.1 on 2026-04-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_app_last_commit_sha'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheVersionIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(db_index=True, max_length=100, unique=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cache Version Index',
                'verbose_name_plural': 'Cache Version Indexes',
                'db_table': 'cache_version_indexes',
            },
        ),
    ]
