# Generated by Django 5.2.1 on 2025-11-29 16:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_service_service_type'),
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('message', models.TextField(help_text='Mensagem do log')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('SUCCESS', 'Success'), ('DOKKU', 'Dokku Output')], default='INFO', max_length=20)),
                ('category', models.CharField(choices=[('SYSTEM', 'Sistema'), ('CREATE', 'Criação'), ('DEPLOY', 'Deploy'), ('CONFIG', 'Configuração'), ('GIT', 'Git'), ('DATABASE', 'Banco de Dados'), ('DOMAIN', 'Domínio'), ('SSL', 'SSL/TLS')], default='SYSTEM', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('progress', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='apps.app')),
            ],
            options={
                'verbose_name': 'App Log',
                'verbose_name_plural': 'App Logs',
                'db_table': 'app_logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Logs',
        ),
        migrations.AddIndex(
            model_name='applog',
            index=models.Index(fields=['app', 'task_id'], name='app_logs_app_id_64461d_idx'),
        ),
        migrations.AddIndex(
            model_name='applog',
            index=models.Index(fields=['app', 'created_at'], name='app_logs_app_id_1ca5bd_idx'),
        ),
    ]
