# Generated by Django 5.2.5 on 2025-08-07 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_django_app', '0002_remove_user_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuarios', to='user_django_app.turma'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ano_nasc',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
    ]
