# Generated by Django 5.2.5 on 2025-08-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_django_app', '0002_remove_user_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
