# Generated by Django 5.2.5 on 2025-08-07 11:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_django_app', '0003_user_turma_alter_user_ano_nasc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ano_nasc',
        ),
        migrations.RemoveField(
            model_name='user',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='user',
            name='turma',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('matricula', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='A matrícula deve conter exatamente 10 números.', regex='^\\d{10}$')], verbose_name='Matrícula')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='user_django_app.turma')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
