# Generated by Django 5.2.16 on 2026-09-22 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        # applications.0001_initial is state-only (SeparateDatabaseAndState) — the real
        # `apps` table is only created once core.apps's migration chain runs. Without this,
        # a fresh DB can apply this migration's real AddField before that table exists.
        ('apps', '0030_delete_cacheversionindex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='created_apps',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
