# Generated by Django 5.2.8 on 2025-11-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_user_git_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registration',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
