# Generated by Django 5.2.8 on 2025-12-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0003_remove_user_registration_user_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='Email do professor/funcionário autorizado', max_length=254, unique=True, verbose_name='E-mail')),
                ('name', models.CharField(blank=True, help_text='Nome do professor/funcionário (opcional)', max_length=255, null=True, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, help_text='Se desativado, o email não terá mais acesso', verbose_name='Ativo')),
                ('notes', models.TextField(blank=True, help_text='Observações sobre este acesso', null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Email Permitido',
                'verbose_name_plural': 'Emails Permitidos',
                'ordering': ['email'],
            },
        ),
    ]
