# Generated by Django 5.2.8 on 2026-02-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0004_allowedemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_fabric',
            field=models.BooleanField(default=False, help_text='Indica se o usuário é membro da Fábrica de Software. Membros podem personalizar nomes de apps.', verbose_name='membro da fábrica'),
        ),
    ]
