# Generated by Django 5.2.5 on 2025-08-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deploy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=200)),
                ('github_repo', models.URLField(blank=True, null=True)),
                ('github_branch', models.CharField(blank=True, default='main', max_length=100, null=True)),
                ('dockerfile_path', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_andamento', 'Em andamento'), ('pronto', 'Pronto'), ('abortado', 'Abortado'), ('erro', 'Erro')], default='rascunho', max_length=20)),
                ('analysis', models.JSONField(blank=True, null=True)),
                ('logs', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Deploy',
                'verbose_name_plural': 'Deploys',
                'ordering': ['-updated_at'],
            },
        ),
    ]
